//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorProcessInfo.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonitorProcessInfo.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Current Process.
        /// </summary>
        public static string GetCurrentProcess_Description {
            get {
                return ResourceManager.GetString("GetCurrentProcess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCurrentProcess.
        /// </summary>
        public static string GetCurrentProcess_DisplayName {
            get {
                return ResourceManager.GetString("GetCurrentProcess_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Process.
        /// </summary>
        public static string GetCurrentProcess_Process_Description {
            get {
                return ResourceManager.GetString("GetCurrentProcess_Process_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string GetCurrentProcess_Process_DisplayName {
            get {
                return ResourceManager.GetString("GetCurrentProcess_Process_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Monitored Value.
        /// </summary>
        public static string GetMonitoredValue_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMonitoredValue.
        /// </summary>
        public static string GetMonitoredValue_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process to get information.
        /// </summary>
        public static string GetMonitoredValue_Process_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_Process_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string GetMonitoredValue_Process_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_Process_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Memory Size (byte).
        /// </summary>
        public static string GetMonitoredValue_ProcessPrivateMemorySize_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessPrivateMemorySize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessPrivateMemorySize.
        /// </summary>
        public static string GetMonitoredValue_ProcessPrivateMemorySize_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessPrivateMemorySize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving Average of Private Memory Size (byte) .
        /// </summary>
        public static string GetMonitoredValue_ProcessPrivateMemorySizeMA_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessPrivateMemorySizeMA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessPrivateMemorySizeMA.
        /// </summary>
        public static string GetMonitoredValue_ProcessPrivateMemorySizeMA_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessPrivateMemorySizeMA_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessResponding.
        /// </summary>
        public static string GetMonitoredValue_ProcessResponding_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessResponding_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessResponding.
        /// </summary>
        public static string GetMonitoredValue_ProcessResponding_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessResponding_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous count of no-responding.
        /// </summary>
        public static string GetMonitoredValue_ProcessRespondingCount_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessRespondingCount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessNoRespondingCount.
        /// </summary>
        public static string GetMonitoredValue_ProcessRespondingCount_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessRespondingCount_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Total Manged Memory from GC (byte).
        /// </summary>
        public static string GetMonitoredValue_ProcessTotalManagedMemory_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessTotalManagedMemory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessTotalMangedMemory.
        /// </summary>
        public static string GetMonitoredValue_ProcessTotalManagedMemory_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessTotalManagedMemory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessTotalProcessorTime (msec).
        /// </summary>
        public static string GetMonitoredValue_ProcessTotalProcessorTime_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessTotalProcessorTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessTotalProcessorTime.
        /// </summary>
        public static string GetMonitoredValue_ProcessTotalProcessorTime_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessTotalProcessorTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessTotalProcessorTimeDelta (msec).
        /// </summary>
        public static string GetMonitoredValue_ProcessTotalProcessorTimeDelta_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessTotalProcessorTimeDelta_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessTotalPTimeDelta.
        /// </summary>
        public static string GetMonitoredValue_ProcessTotalProcessorTimeDelta_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessTotalProcessorTimeDelta_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process workingset (byte).
        /// </summary>
        public static string GetMonitoredValue_ProcessWorkingSet_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessWorkingSet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessWorkingSet.
        /// </summary>
        public static string GetMonitoredValue_ProcessWorkingSet_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessWorkingSet_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving average of workingset (byte).
        /// </summary>
        public static string GetMonitoredValue_ProcessWorkingSetMA_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessWorkingSetMA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessWorkingSetMA.
        /// </summary>
        public static string GetMonitoredValue_ProcessWorkingSetMA_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessWorkingSetMA_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw value dictionary of result.
        /// </summary>
        public static string GetMonitoredValue_RawValue_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_RawValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawValue.
        /// </summary>
        public static string GetMonitoredValue_RawValue_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_RawValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Available Physical Memory (byte).
        /// </summary>
        public static string GetMonitoredValue_SystemAvailablePhysicalMemory_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemAvailablePhysicalMemory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAvilablePhysicalMemory.
        /// </summary>
        public static string GetMonitoredValue_SystemAvailablePhysicalMemory_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemAvailablePhysicalMemory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Available Virtual Memory (byte).
        /// </summary>
        public static string GetMonitoredValue_SystemAvailableVirtualMemory_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemAvailableVirtualMemory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAvilableVirtualMemory.
        /// </summary>
        public static string GetMonitoredValue_SystemAvailableVirtualMemory_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemAvailableVirtualMemory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Each Cpu (%).
        /// </summary>
        public static string GetMonitoredValue_SystemEachCpu_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemEachCpu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemEachCpu.
        /// </summary>
        public static string GetMonitoredValue_SystemEachCpu_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemEachCpu_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total CPU through the system. (%).
        /// </summary>
        public static string GetMonitoredValue_SystemTotalCpu_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalCpu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemTotalCPU.
        /// </summary>
        public static string GetMonitoredValue_SystemTotalCpu_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalCpu_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving average of Total CPU through the system. (%).
        /// </summary>
        public static string GetMonitoredValue_SystemTotalCpuMA_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalCpuMA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemTotalCPU MA.
        /// </summary>
        public static string GetMonitoredValue_SystemTotalCpuMA_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalCpuMA_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Total Physical Memory (byte).
        /// </summary>
        public static string GetMonitoredValue_SystemTotalPhysicalMemory_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalPhysicalMemory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemTotalPhysicalMemory.
        /// </summary>
        public static string GetMonitoredValue_SystemTotalPhysicalMemory_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalPhysicalMemory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Total Virtual Memory (byte).
        /// </summary>
        public static string GetMonitoredValue_SystemTotalVirtualMemory_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalVirtualMemory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemTotalVirtualMemory.
        /// </summary>
        public static string GetMonitoredValue_SystemTotalVirtualMemory_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalVirtualMemory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Process from UiPath.Core.Window.
        /// </summary>
        public static string GetProcessFromMainWindow_Description {
            get {
                return ResourceManager.GetString("GetProcessFromMainWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProcessFromMainWindow.
        /// </summary>
        public static string GetProcessFromMainWindow_DisplayName {
            get {
                return ResourceManager.GetString("GetProcessFromMainWindow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string GetProcessFromMainWindow_Process_Description {
            get {
                return ResourceManager.GetString("GetProcessFromMainWindow_Process_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string GetProcessFromMainWindow_Process_DisplayName {
            get {
                return ResourceManager.GetString("GetProcessFromMainWindow_Process_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UiPath.Core.Window.
        /// </summary>
        public static string GetProcessFromMainWindow_Window_Description {
            get {
                return ResourceManager.GetString("GetProcessFromMainWindow_Window_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string GetProcessFromMainWindow_Window_DisplayName {
            get {
                return ResourceManager.GetString("GetProcessFromMainWindow_Window_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope for Monitor Process Information.
        /// </summary>
        public static string MonitorProcessInfoScope_Description {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonitorProcessInfoScope.
        /// </summary>
        public static string MonitorProcessInfoScope_DisplayName {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval for getting process info (sec).
        /// </summary>
        public static string MonitorProcessInfoScope_Interval_Description {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Interval_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string MonitorProcessInfoScope_Interval_DisplayName {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Interval_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director for logging.
        /// </summary>
        public static string MonitorProcessInfoScope_LogDirectory_Description {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_LogDirectory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogDirectory.
        /// </summary>
        public static string MonitorProcessInfoScope_LogDirectory_DisplayName {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_LogDirectory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable logging or not.
        /// </summary>
        public static string MonitorProcessInfoScope_Logging_Description {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Logging_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string MonitorProcessInfoScope_Logging_DisplayName {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Logging_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number for calculate moving average.
        /// </summary>
        public static string MonitorProcessInfoScope_Number_Description {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Number_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string MonitorProcessInfoScope_Number_DisplayName {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Number_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string MonitorProcessInfoScope_Process_Description {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Process_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string MonitorProcessInfoScope_Process_DisplayName {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Process_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of {0} shoud be more than 0..
        /// </summary>
        public static string MonitorProcessInfoScope_ValidationMsg_Not_Positive {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_ValidationMsg_Not_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output - Process.
        /// </summary>
        public static string Process_Category {
            get {
                return ResourceManager.GetString("Process_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set process to monitor.
        /// </summary>
        public static string SetMonitorProcess_Description {
            get {
                return ResourceManager.GetString("SetMonitorProcess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMonitorProcess.
        /// </summary>
        public static string SetMonitorProcess_DisplayName {
            get {
                return ResourceManager.GetString("SetMonitorProcess_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process to monitor.
        /// </summary>
        public static string SetMonitorProcess_Process_Description {
            get {
                return ResourceManager.GetString("SetMonitorProcess_Process_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string SetMonitorProcess_Process_DisplayName {
            get {
                return ResourceManager.GetString("SetMonitorProcess_Process_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output - System.
        /// </summary>
        public static string System_Category {
            get {
                return ResourceManager.GetString("System_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
