//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorProcessInfo.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonitorProcessInfo.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Authentication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If set, continue executing the remaining activities even if the current activity has failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContinueOnError に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get Current Process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetCurrentProcess_Description {
            get {
                return ResourceManager.GetString("GetCurrentProcess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetCurrentProcess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetCurrentProcess_DisplayName {
            get {
                return ResourceManager.GetString("GetCurrentProcess_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetCurrentProcess_Process_Description {
            get {
                return ResourceManager.GetString("GetCurrentProcess_Process_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetCurrentProcess_Process_DisplayName {
            get {
                return ResourceManager.GetString("GetCurrentProcess_Process_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get Monitored Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetMonitoredValue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process to get information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_Process_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_Process_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_Process_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_Process_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Private Memory Size (byte) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessPrivateMemorySize_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessPrivateMemorySize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProcessPrivateMemorySize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessPrivateMemorySize_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessPrivateMemorySize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moving Average of Private Memory Size (byte)  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessPrivateMemorySizeMA_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessPrivateMemorySizeMA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProcessPrivateMemorySizeMA に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessPrivateMemorySizeMA_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessPrivateMemorySizeMA_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProcessResponding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessResponding_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessResponding_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProcessResponding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessResponding_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessResponding_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continuous count of no-responding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessRespondingCount_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessRespondingCount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProcessNoRespondingCount に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessRespondingCount_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessRespondingCount_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process Total Manged Memory from GC (byte) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessTotalManagedMemory_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessTotalManagedMemory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProcessTotalMangedMemory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessTotalManagedMemory_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessTotalManagedMemory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProcessTotalProcessorTime (msec) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessTotalProcessorTime_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessTotalProcessorTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProcessTotalProcessorTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessTotalProcessorTime_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessTotalProcessorTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProcessTotalProcessorTimeDelta (msec) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessTotalProcessorTimeDelta_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessTotalProcessorTimeDelta_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProcessTotalPTimeDelta に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessTotalProcessorTimeDelta_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessTotalProcessorTimeDelta_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process workingset (byte) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessWorkingSet_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessWorkingSet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProcessWorkingSet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessWorkingSet_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessWorkingSet_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moving average of workingset (byte) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessWorkingSetMA_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessWorkingSetMA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProcessWorkingSetMA に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_ProcessWorkingSetMA_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_ProcessWorkingSetMA_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Raw value dictionary of result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_RawValue_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_RawValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RawValue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_RawValue_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_RawValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Available Physical Memory (byte) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_SystemAvailablePhysicalMemory_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemAvailablePhysicalMemory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SystemAvilablePhysicalMemory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_SystemAvailablePhysicalMemory_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemAvailablePhysicalMemory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Available Virtual Memory (byte) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_SystemAvailableVirtualMemory_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemAvailableVirtualMemory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SystemAvilableVirtualMemory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_SystemAvailableVirtualMemory_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemAvailableVirtualMemory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List of Each Cpu (%) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_SystemEachCpu_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemEachCpu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SystemEachCpu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_SystemEachCpu_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemEachCpu_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total CPU through the system. (%) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_SystemTotalCpu_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalCpu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SystemTotalCPU に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_SystemTotalCpu_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalCpu_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moving average of Total CPU through the system. (%) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_SystemTotalCpuMA_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalCpuMA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SystemTotalCPU MA に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_SystemTotalCpuMA_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalCpuMA_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Total Physical Memory (byte) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_SystemTotalPhysicalMemory_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalPhysicalMemory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SystemTotalPhysicalMemory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_SystemTotalPhysicalMemory_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalPhysicalMemory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Total Virtual Memory (byte) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_SystemTotalVirtualMemory_Description {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalVirtualMemory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SystemTotalVirtualMemory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetMonitoredValue_SystemTotalVirtualMemory_DisplayName {
            get {
                return ResourceManager.GetString("GetMonitoredValue_SystemTotalVirtualMemory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get Process from UiPath.Core.Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetProcessFromMainWindow_Description {
            get {
                return ResourceManager.GetString("GetProcessFromMainWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetProcessFromMainWindow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetProcessFromMainWindow_DisplayName {
            get {
                return ResourceManager.GetString("GetProcessFromMainWindow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetProcessFromMainWindow_Process_Description {
            get {
                return ResourceManager.GetString("GetProcessFromMainWindow_Process_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetProcessFromMainWindow_Process_DisplayName {
            get {
                return ResourceManager.GetString("GetProcessFromMainWindow_Process_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UiPath.Core.Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetProcessFromMainWindow_Window_Description {
            get {
                return ResourceManager.GetString("GetProcessFromMainWindow_Window_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GetProcessFromMainWindow_Window_DisplayName {
            get {
                return ResourceManager.GetString("GetProcessFromMainWindow_Window_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scope for Monitor Process Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonitorProcessInfoScope_Description {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MonitorProcessInfoScope に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonitorProcessInfoScope_DisplayName {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval for getting process info (sec) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonitorProcessInfoScope_Interval_Description {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Interval_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonitorProcessInfoScope_Interval_DisplayName {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Interval_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number for calculate moving average に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonitorProcessInfoScope_Number_Description {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Number_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonitorProcessInfoScope_Number_DisplayName {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Number_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonitorProcessInfoScope_Process_Description {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Process_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonitorProcessInfoScope_Process_DisplayName {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_Process_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value of {0} shoud be more than 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonitorProcessInfoScope_ValidationMsg_Not_Positive {
            get {
                return ResourceManager.GetString("MonitorProcessInfoScope_ValidationMsg_Not_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output - Process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Process_Category {
            get {
                return ResourceManager.GetString("Process_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set process to monitor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetMonitorProcess_Description {
            get {
                return ResourceManager.GetString("SetMonitorProcess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SetMonitorProcess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetMonitorProcess_DisplayName {
            get {
                return ResourceManager.GetString("SetMonitorProcess_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process to monitor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetMonitorProcess_Process_Description {
            get {
                return ResourceManager.GetString("SetMonitorProcess_Process_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetMonitorProcess_Process_DisplayName {
            get {
                return ResourceManager.GetString("SetMonitorProcess_Process_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output - System に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string System_Category {
            get {
                return ResourceManager.GetString("System_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout (milliseconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The activity timed out and was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a value either for {0} or {1}, but not both. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide values for both {0} and {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot be used outside of a {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a value for {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
